### ISSUE TITLE
Лишние данные

### ISSUE THREAD

**Issue by korvin001** [robocupmipt/graph#4]
не нужны:
https://github.com/robocupmipt/graph/blob/1b5cb2c1827adaa64d16b357fdf3e8ba326d2ca6/graph.h#L14
https://github.com/robocupmipt/graph/blob/1b5cb2c1827adaa64d16b357fdf3e8ba326d2ca6/graph.h#L15

**Comment by nevstruevdmitriy** [comment]
fixed
